name: drive_master
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  percent_indicator: ^4.2.2
  flutter_launcher_icons: ^0.14.1
  firebase_storage: ^12.3.5
  image_picker: ^0.8.5+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0




flutter:
  uses-material-design: true

  # Agrega la sección de assets y especifica la ruta de la imagen
  assets:
    - assets/images/background.png
    - assets/images/drivemaster.png
    - assets/scenes/3yhqgMqQpS5e4OdRET6b.png
    - assets/scenes/4acuivdR948JROIS8kDU.png
    - assets/scenes/G3kHTVO3a8G1rpsGuyZx.png
    - assets/scenes/UWjScFLF6C5Mwn2r5Sp9.png
