// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoYoxoVCC7IJAf62jiwJx5fdcIzVT60fo',
    appId: '1:274521845514:web:27a027d9a2db8024a614f3',
    messagingSenderId: '274521845514',
    projectId: 'drive-master-b4744',
    authDomain: 'drive-master-b4744.firebaseapp.com',
    storageBucket: 'drive-master-b4744.firebasestorage.app',
    measurementId: 'G-N1PTN6FZ6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZJgn-oTVXadZqs-_974AWqVTmHWQPh_U',
    appId: '1:274521845514:android:488887c0508a030da614f3',
    messagingSenderId: '274521845514',
    projectId: 'drive-master-b4744',
    storageBucket: 'drive-master-b4744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNvvlCJFpxn1OUDqdfmEdfb1o-M-0nLmY',
    appId: '1:274521845514:ios:8c4feaf241ec5dc4a614f3',
    messagingSenderId: '274521845514',
    projectId: 'drive-master-b4744',
    storageBucket: 'drive-master-b4744.firebasestorage.app',
    iosBundleId: 'com.example.driveMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNvvlCJFpxn1OUDqdfmEdfb1o-M-0nLmY',
    appId: '1:274521845514:ios:8c4feaf241ec5dc4a614f3',
    messagingSenderId: '274521845514',
    projectId: 'drive-master-b4744',
    storageBucket: 'drive-master-b4744.firebasestorage.app',
    iosBundleId: 'com.example.driveMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoYoxoVCC7IJAf62jiwJx5fdcIzVT60fo',
    appId: '1:274521845514:web:f1db1f6cb2801e96a614f3',
    messagingSenderId: '274521845514',
    projectId: 'drive-master-b4744',
    authDomain: 'drive-master-b4744.firebaseapp.com',
    storageBucket: 'drive-master-b4744.firebasestorage.app',
    measurementId: 'G-X10J28FZSB',
  );
}
